<a href="https://colab.research.google.com/github/Mrinal0044/Machine-Learning/blob/main/One_Hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.one hot encoding is used for NOMINAL categorical data.

2.It is very important to convert string categorical data into numerical data and hence this technique is used.

3.We convert it into vector.

4.We convert each category into a new column. eg- if we have 50 categories , 50 new columns will be created and then vectorize it .

5.But due to "multicollinearity" and to avoid inter dependency between input or dummy variable trap columns we use n-1 columns .

In [1]:
import numpy as np
import pandas as pd

In [4]:
df= pd.read_csv("/content/cars.csv")

In [5]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [7]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [9]:
df['brand'].nunique()

32

In [10]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [11]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

1.One hot encoding using pandas

In [13]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

2. k-1 one hot encoding

In [15]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In ML , we use sklearn

3. one hot encoding using sklearn

In [16]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest= train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=True)

In [17]:
xtrain.head()

        brand  km_driven    fuel         owner
1939    Honda     100000  Diesel  Second Owner
5455   Maruti     120000  Diesel  Second Owner
7079  Renault     100000  Diesel  Second Owner
2000    Honda      80000  Petrol  Second Owner
1578    Honda      56494  Petrol   First Owner

In [18]:
xtest.head()

         brand  km_driven    fuel        owner
1392  Mahindra      80000  Diesel  First Owner
7778      Tata      45000  Diesel  First Owner
3727   Hyundai      60000  Diesel  First Owner
6630      Tata      15000  Petrol  First Owner
103     Maruti     100000  Petrol  Third Owner

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [24]:
ohe= OneHotEncoder(drop='first', sparse_output=False)

here drop =first will remove the first column to avoid multicollinearity

In [25]:
xtrain_new = ohe.fit_transform(xtrain[['fuel', 'owner']])

In [26]:
xtest_new= ohe.transform(xtest[['fuel','owner']])

In [27]:
xtrain_new.shape

(6502, 7)

In [28]:
np.hstack((xtrain[['brand','km_driven']].values,xtrain_new)).shape

(6502, 9)

4. one hot encoding with top categories

In [29]:
counts = df['brand'].value_counts()

In [30]:
df['brand'].nunique()
threshold=100

In [31]:
repl = counts[counts <= threshold].index

In [32]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
1418,False,False,False,False,False,False,True,False,False,False,False,False,False
1291,False,False,False,False,False,False,False,False,False,True,False,False,False
1164,False,False,False,False,False,False,True,False,False,False,False,False,False
3843,False,False,False,False,False,False,True,False,False,False,False,False,False
7839,False,False,False,False,False,False,False,False,False,False,True,False,False