<a href="https://colab.research.google.com/github/Mrinal0044/Machine-Learning/blob/main/ordinal_and_label_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [4]:
df= pd.read_csv("/customer.csv")

In [5]:
df.sample(3)

    age  gender review education purchased
16   59    Male   Poor        UG       Yes
15   75    Male   Poor        UG        No
26   53  Female   Poor        PG        No

review and education is the ordinal categorical data column. Gender, review, education  are categorical.

Review and education - ordinal encoding
Purchase- label encoding

In [6]:
df= df.iloc[:,2:]

In [7]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [9]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

firstly, split train test

In [11]:
x_train, x_test, y_train, y_test= train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [12]:
x_train

     review education
25     Good    School
26     Poor        PG
43     Poor        PG
42     Good        PG
3      Good        PG
19     Poor        PG
32  Average        UG
20  Average    School
29  Average        UG
40     Good    School
1      Poor        UG
28     Poor    School
33     Good        PG
9      Good        UG
49     Good        UG
23     Good    School
18     Good    School
17     Poor        UG
21  Average        PG
47     Good        PG
14     Poor        PG
36     Good        UG
27     Poor        PG
16     Poor        UG
41     Good        PG
39     Poor        PG
12     Poor    School
10     Good        UG
24  Average        PG
35     Poor    School
8   Average        UG
11     Good        UG
37  Average        PG
34  Average    School
48     Good        UG
31     Poor    School
7      Poor    School
22     Poor        PG
0   Average    School
15     Poor        UG

In [13]:
oe= OrdinalEncoder(categories=[['Poor','Average','Good'], ['School', 'UG', 'PG']])

make sure to pass the values inside list according to importance . good and pg have more weightage

FIT FIRST THEN TRANSFORM

In [14]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [15]:
x_train= oe.transform(x_train)
x_test= oe.transform(x_test)

In [16]:
x_train

array([[2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [0., 1.]])

it has transformed the columns and given them values

In [17]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

LABEL ENCODING IS EXCUSIVELY FOR OUTPUT COLUMN

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le= LabelEncoder()

In [20]:
le.fit(y_train)

LabelEncoder()

In [22]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [23]:
y_train= le.transform(y_train)
y_test= le.transform(y_test)

In [24]:
y_train

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0])